config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :products
	root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_user!, except: [:index]
	
	def index
		@items = Item.all
		@count = Item.count
	end

	def show
		@item = Item.find(params[:id])
	end

	def new
		@item = Item.new
	end

	def create
		@item = Item.new item_params
		@item.user = 
		if @item.save
			redirect_to product_path(@item)
		else
			render 'new'
		end
	end

	private

	def item_params
		params.require(:item).permit(:name, :category, :description, :tags, :availability, :availability_count, :price)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  	<header id="header">
      <div class="header_inner">
        <%= link_to "Home","#" %>
        <nav>
          <% if user_signed_in? %>
            <%= link_to "Hello #{current_user.email.split('@')[0].capitalize}", "#" %>
            <% if current_user && current_user.admin %>
              <%= link_to "New Product", new_product_path %>
            <% end %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
            <%= link_to "Cart", "#" %>
          <% else %>
          	<%= link_to "Sign Up", new_user_registration_path %>
            <%= link_to "Log In", new_user_session_path %>
          <% end %>          
        </nav>
      </div>
    </header>  
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<br><br>
<%= form_for @item, url: :products, method: :post do |f| %>
	
	<%= f.label :name %><br>
	<%= f.text_field :name %><br>

	<%= f.label :category %><br>
	<%= f.text_field :category %><br>

	<%= f.label :description %><br>
	<%= f.text_field :description %><br>

	<%= f.label :tags %><br>
	<%= f.text_field :tags %><br>

	<%= f.label :availability %><br>
	<%= f.text_field :availability %><br>

	<%= f.label :availability_count %><br>
	<%= f.text_field :availability_count %><br>

	<%= f.label :price %><br>
	<%= f.text_field :price %><br>

	<%= f.submit %><br>
	
<% end %>

app/views/products/index.html.erb
<div class="container">
	<h1>Products Available</h1>
	<p>Total item: <%= @count %></p>
	<% @items.each do |item| %>
		<div>
			<p>Name: <%= link_to item.name, product_path(item) %></p>
			<p>Category: <%= item.category %></p>
			<p>Description: <%= item.description %></p>
			<p>Tag: <%= item.tags %></p>
			<p>Availability: <%= item.availability %></p>
			<p>Item Count : <%= item.availability_count %></p>
			<p>Price: <%= item.price %></p>
			<p><%= link_to "Add Product To Cart", "#" %></p>
			<br><br>
		</div>
	<% end %>
</div>

app/views/products/new.html.erb
<div class="container">
	<%= render 'form' %>
</div>

app/views/products/show.html.erb
<div class="container">
	<h2>Showing Item</h2>
	<p>Name: <%= @item.name %></p>
	<p>Category: <%= @item.category %></p>
	<p>Description: <%= @item.description %></p>
	<p>Tag: <%= @item.tags %></p>
	<p>Availability: <%= @item.availability %></p>
	<p>Item Count : <%= @item.availability_count %></p>
	<p>Price: <%= @item.price %></p>
	<%= link_to "Add to cart", "#", class: "btn btn-primary"  %>
	<%= link_to "Back", products_path, class: "btn btn-primary" %>
</div>